name: coffe_clock
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  matrix4_transform: ^1.1.3
  flutter_screenutil: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SpecialElite
      fonts:
        - asset: third_party/Special_Elite/SpecialElite-Regular.ttf
    - family: Caveat
      fonts:
        - asset: third_party/Caveat/Caveat-Regular.ttf
  assets:
    - assets/imgs/background_dark.png
    - assets/imgs/background_light.png
    - assets/imgs/pencil_1.png
    - assets/imgs/pencil_2.png